lines = []
def L(s): lines.append(s)

# DOM refs + theme + hamburger + logout
L("  // ---- DOM refs ----")
L("  var feedEl = document.getElementById('profile-posts');")
L("  var statusEl = document.getElementById('profile-post-status');")
L("  var actionModal = document.getElementById('action-modal');")
L("  var actionModalTitle = document.getElementById('action-modal-title');")
L("  var actionModalMessage = document.getElementById('action-modal-message');")
L("  var actionModalInput = document.getElementById('action-modal-input');")
L("  var actionModalError = document.getElementById('action-modal-error');")
L("  var actionModalCancel = document.getElementById('action-modal-cancel');")
L("  var actionModalConfirm = document.getElementById('action-modal-confirm');")
L("  var modalConfirmHandler = null;")
L("")
L("  // ---- Theme ----")
L("  var hamburgerBtn = document.getElementById('hamburger-btn');")
L("  var hamburgerMenu = document.getElementById('hamburger-menu');")
L("  var settingsItem = document.getElementById('settings-item');")
L("  var settingsSubmenu = document.getElementById('settings-submenu');")
L("  var themeLightBtn = document.getElementById('theme-light-btn');")
L("  var themeDarkBtn = document.getElementById('theme-dark-btn');")
L("")
L("  function applyTheme(theme) {")
L("    if (theme === 'dark') {")
L("      document.documentElement.setAttribute('data-theme', 'dark');")
L("      themeDarkBtn.classList.add('active');")
L("      themeDarkBtn.setAttribute('aria-pressed', 'true');")
L("      themeLightBtn.classList.remove('active');")
L("      themeLightBtn.setAttribute('aria-pressed', 'false');")
L("    } else {")
L("      document.documentElement.removeAttribute('data-theme');")
L("      themeLightBtn.classList.add('active');")
L("      themeLightBtn.setAttribute('aria-pressed', 'true');")
L("      themeDarkBtn.classList.remove('active');")
L("      themeDarkBtn.setAttribute('aria-pressed', 'false');")
L("    }")
L("    try { localStorage.setItem('ub_theme', theme); } catch (e) {}")
L("  }")
L("")
L("  try { applyTheme(localStorage.getItem('ub_theme') || 'light'); } catch (e) { applyTheme('light'); }")
L("")
L("  function closeHamburger() {")
L("    hamburgerMenu.classList.add('hidden');")
L("    hamburgerBtn.setAttribute('aria-expanded', 'false');")
L("  }")
L("")
L("  hamburgerBtn.addEventListener('click', function (e) {")
L("    e.stopPropagation();")
L("    var isOpen = !hamburgerMenu.classList.contains('hidden');")
L("    if (isOpen) { closeHamburger(); } else {")
L("      hamburgerMenu.classList.remove('hidden');")
L("      hamburgerBtn.setAttribute('aria-expanded', 'true');")
L("    }")
L("  });")
L("")
L("  settingsItem.addEventListener('click', function (e) {")
L("    e.stopPropagation();")
L("    settingsSubmenu.classList.toggle('hidden');")
L("    var chevron = settingsItem.querySelector('.chevron-icon');")
L("    if (chevron) chevron.style.transform = settingsSubmenu.classList.contains('hidden') ? '' : 'rotate(180deg)';")
L("  });")
L("")
L("  document.addEventListener('click', function () {")
L("    closeHamburger();")
L("    settingsSubmenu.classList.add('hidden');")
L("  });")
L("")
L("  hamburgerMenu.addEventListener('click', function (e) { e.stopPropagation(); });")
L("  themeLightBtn.addEventListener('click', function () { applyTheme('light'); });")
L("  themeDarkBtn.addEventListener('click', function () { applyTheme('dark'); });")
L("")
L("  document.getElementById('btn-logout').addEventListener('click', function () {")
L("    try { sessionStorage.removeItem(STORAGE_KEY); } catch (e) {}")
L("    window.location.href = '/';")
L("  });")

with open('_p2.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('p2 done:', len(lines))
