# Generate profile.js
import sys

lines = []

def L(s):
    lines.append(s)

# IIFE start + constants
L("(function () {")
L("  var STORAGE_KEY = 'ub_session';")
L("  var REACTION_TYPES = ['heart', 'haha', 'wow', 'sad', 'angry'];")
L("  var REACTION_EMOJI = { heart: '\u2764\ufe0f', haha: '\U0001f602', wow: '\U0001f62e', sad: '\U0001f622', angry: '\U0001f621' };")
L("  var currentUser = null;")
L("  var viewedUserId = null;")
L("")
L("  // ---- Session ----")
L("  function ensureSession() {")
L("    try {")
L("      var raw = sessionStorage.getItem(STORAGE_KEY);")
L("      if (!raw) { window.location.href = '/'; return false; }")
L("      var parsed = JSON.parse(raw);")
L("      if (!parsed || !parsed.user_id) { window.location.href = '/'; return false; }")
L("      currentUser = parsed;")
L("      return true;")
L("    } catch (e) { window.location.href = '/'; return false; }")
L("  }")
L("  if (!ensureSession()) return;")
L("")
L("  function getReactionToken() { return 'user_' + String(currentUser.user_id); }")
L("")
L("  // ---- Helpers ----")
L("  function escapeHtml(s) {")
L("    var d = document.createElement('div');")
L("    d.textContent = s;")
L("    return d.innerHTML;")
L("  }")
L("")
L("  function initials(name) {")
L("    var clean = (name || '').trim();")
L("    if (!clean) return 'U';")
L("    var parts = clean.split(/\\s+/).slice(0, 2);")
L("    return parts.map(function (p) { return p.charAt(0).toUpperCase(); }).join('');")
L("  }")
L("")
L("  function avatarHtml(url, name, className) {")
L("    if (url) {")
L("      return '<img class=\"' + className + '\" src=\"' + escapeHtml(url) + '\" alt=\"' + escapeHtml(name || 'User') + '\" />';")
L("    }")
L("    return '<div class=\"' + className + ' no-image\" aria-hidden=\"true\">' + escapeHtml(initials(name)) + '</div>';")
L("  }")
L("")
L("  function profileHref(userId) {")
L("    return '/profile/' + encodeURIComponent(String(userId || ''));")
L("  }")
L("")
L("  function editedLabel(item) {")
L("    if (!item || !item.updated_at) return '';")
L("    return ' <span class=\"edited-label\">(edited)</span>';")
L("  }")
L("")
L("  function parseUtcDate(iso) {")
L("    if (!iso) return new Date(NaN);")
L("    var s = String(iso).trim();")
L("    if (!/[Zz+\\-]\\d*$/.test(s)) s += 'Z';")
L("    return new Date(s);")
L("  }")
L("")
L("  function formatDate(iso) {")
L("    try { return parseUtcDate(iso).toLocaleString(); } catch (e) { return iso; }")
L("  }")
L("")
L("  function formatRelativeTime(iso) {")
L("    try {")
L("      var d = parseUtcDate(iso);")
L("      var sec = Math.floor((Date.now() - d.getTime()) / 1000);")
L("      if (sec < 10) return 'just now';")
L("      if (sec < 60) return sec + ' sec ago';")
L("      if (sec < 3600) return Math.floor(sec / 60) + ' min ago';")
L("      if (sec < 86400) return Math.floor(sec / 3600) + ' h ago';")
L("      if (sec < 604800) return Math.floor(sec / 86400) + ' d ago';")
L("      return formatDate(iso);")
L("    } catch (e) { return iso; }")
L("  }")
L("")
L("  function formatJoinDate(iso) {")
L("    try {")
L("      var d = parseUtcDate(iso);")
L("      var months = ['January','February','March','April','May','June','July','August','September','October','November','December'];")
L("      return 'Joined on ' + months[d.getUTCMonth()] + ' ' + d.getUTCDate() + ', ' + d.getUTCFullYear();")
L("    } catch (e) { return ''; }")
L("  }")
L("")
L("  // ---- API ----")
L("  function api(path, opts) {")
L("    return fetch(path, opts).then(function (r) {")
L("      var ct = r.headers.get('content-type') || '';")
L("      if (ct.indexOf('application/json') !== -1) {")
L("        return r.json().then(function (j) {")
L("          if (!r.ok) throw new Error(j.error || r.statusText);")
L("          return j;")
L("        });")
L("      }")
L("      if (!r.ok) throw new Error(r.statusText);")
L("      return {};")
L("    });")
L("  }")

with open('_profile_part1.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('part1 ok, lines:', len(lines))
