lines = []
def L(s): lines.append(s)

# Action modal
L("  // ---- Action Modal ----")
L("  function closeActionModal() {")
L("    actionModal.classList.add('hidden');")
L("    actionModal.setAttribute('aria-hidden', 'true');")
L("    actionModalError.textContent = '';")
L("    actionModalError.classList.add('hidden');")
L("    modalConfirmHandler = null;")
L("  }")
L("")
L("  function openActionModal(config) {")
L("    actionModalTitle.textContent = config.title || 'Confirm';")
L("    actionModalMessage.textContent = config.message || '';")
L("    actionModalInput.classList.toggle('hidden', !config.showInput);")
L("    actionModalInput.value = config.initialValue || '';")
L("    actionModalError.textContent = '';")
L("    actionModalError.classList.add('hidden');")
L("    actionModalConfirm.textContent = config.confirmText || 'Confirm';")
L("    actionModalConfirm.classList.toggle('btn-danger', !!config.danger);")
L("    actionModal.classList.remove('hidden');")
L("    actionModal.setAttribute('aria-hidden', 'false');")
L("    modalConfirmHandler = config.onConfirm || null;")
L("    if (config.showInput) actionModalInput.focus();")
L("  }")
L("")
L("  actionModalCancel.addEventListener('click', closeActionModal);")
L("  actionModal.addEventListener('click', function (e) {")
L("    if (e.target === actionModal) closeActionModal();")
L("  });")
L("  var actionModalCard = document.querySelector('.action-modal-card');")
L("  if (actionModalCard) actionModalCard.addEventListener('click', function (e) { e.stopPropagation(); });")
L("  actionModalConfirm.addEventListener('click', function () {")
L("    if (!modalConfirmHandler) { closeActionModal(); return; }")
L("    modalConfirmHandler({")
L("      value: (actionModalInput.value || '').trim(),")
L("      setError: function (msg) {")
L("        actionModalError.textContent = msg || '';")
L("        actionModalError.classList.toggle('hidden', !msg);")
L("      },")
L("      close: closeActionModal")
L("    });")
L("  });")
L("")
L("  // ---- Owner menu ----")
L("  function bindOwnerMenu(container) {")
L("    var trigger = container.querySelector('.owner-menu-trigger');")
L("    var menu = container.querySelector('.owner-menu-list');")
L("    if (!trigger || !menu) return;")
L("    trigger.addEventListener('click', function (e) {")
L("      e.stopPropagation();")
L("      menu.classList.toggle('hidden');")
L("    });")
L("    document.addEventListener('click', function () { menu.classList.add('hidden'); });")
L("    menu.addEventListener('click', function (e) { e.stopPropagation(); });")
L("  }")
L("")
L("  // ---- Enter to submit ----")
L("  function bindEnterToSubmit(textareaEl, submitFn) {")
L("    if (!textareaEl) return;")
L("    textareaEl.addEventListener('keydown', function (e) {")
L("      if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitFn(); }")
L("    });")
L("  }")

with open('_p3.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('p3 done:', len(lines))
